2024-05-30 15:34:20|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:34:20|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:34:20|   DEBUG|testAction.py[:57]|kkkk
2024-05-30 15:34:20|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:34:20|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:34:20|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:34:20|   DEBUG|testAction.py[:57]|llll
2024-05-30 15:34:20|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:34:20|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:34:20|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:34:20|   DEBUG|testAction.py[:57]|oooo
2024-05-30 15:34:20|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:34:20|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:34:21|   DEBUG|testAction.py[:57]|pppp
2024-05-30 15:34:21|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:34:21|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:34:21|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:34:21|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:34:21|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:34:21|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:37:02|   DEBUG|testAction.py[:218]|1
2024-05-30 15:37:02|   DEBUG|testAction.py[:219]|10
2024-05-30 15:37:02|   DEBUG|testAction.py[:223]|0
2024-05-30 15:37:02|   DEBUG|testAction.py[:224]|10
2024-05-30 15:37:03|   DEBUG|testAction.py[:218]|1
2024-05-30 15:37:03|   DEBUG|testAction.py[:219]|10
2024-05-30 15:37:03|   DEBUG|testAction.py[:223]|0
2024-05-30 15:37:03|   DEBUG|testAction.py[:224]|10
2024-05-30 15:37:04|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:37:07|   DEBUG|testAction.py[:218]|1
2024-05-30 15:37:07|   DEBUG|testAction.py[:219]|10
2024-05-30 15:37:07|   DEBUG|testAction.py[:223]|0
2024-05-30 15:37:07|   DEBUG|testAction.py[:224]|10
2024-05-30 15:39:15|   DEBUG|testAction.py[:57]|admin
2024-05-30 15:39:15|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:15|   DEBUG|testAction.py[:57]|sniper
2024-05-30 15:39:15|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:15|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:15|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:15|   DEBUG|testAction.py[:57]|sniper
2024-05-30 15:39:15|   DEBUG|testAction.py[:58]|111111
2024-05-30 15:39:15|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2024-05-30 15:39:15|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2024-05-30 15:39:15|   DEBUG|testAction.py[:57]|apple
2024-05-30 15:39:15|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:15|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:15|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:15|   DEBUG|testAction.py[:57]|aaaa
2024-05-30 15:39:15|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:15|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:15|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:15|   DEBUG|testAction.py[:57]|bbbb
2024-05-30 15:39:15|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:15|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:15|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:15|   DEBUG|testAction.py[:57]|cccc
2024-05-30 15:39:15|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|dddd
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|eeee
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|ffff
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|hhhh
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|gggg
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|iiii
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|jjjj
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|kkkk
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:16|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:16|   DEBUG|testAction.py[:57]|llll
2024-05-30 15:39:16|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:17|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:17|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:17|   DEBUG|testAction.py[:57]|oooo
2024-05-30 15:39:17|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:17|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:17|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:17|   DEBUG|testAction.py[:57]|pppp
2024-05-30 15:39:17|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:39:17|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:17|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:39:17|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:39:17|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:26|   DEBUG|testAction.py[:57]|admin
2024-05-30 15:45:26|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:26|   DEBUG|testAction.py[:57]|sniper
2024-05-30 15:45:26|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:26|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:26|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:26|   DEBUG|testAction.py[:57]|sniper
2024-05-30 15:45:26|   DEBUG|testAction.py[:58]|111111
2024-05-30 15:45:26|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|apple
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|aaaa
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|bbbb
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|cccc
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|dddd
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|eeee
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|ffff
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|hhhh
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:27|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:27|   DEBUG|testAction.py[:57]|gggg
2024-05-30 15:45:27|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:27|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   DEBUG|testAction.py[:57]|iiii
2024-05-30 15:45:28|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|   DEBUG|testAction.py[:57]|jjjj
2024-05-30 15:45:28|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   DEBUG|testAction.py[:57]|kkkk
2024-05-30 15:45:28|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|   DEBUG|testAction.py[:57]|llll
2024-05-30 15:45:28|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|   DEBUG|testAction.py[:57]|oooo
2024-05-30 15:45:28|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|   DEBUG|testAction.py[:57]|pppp
2024-05-30 15:45:28|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:45:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:45:28|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:45:28|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:51:51|   DEBUG|testAction.py[:57]|admin
2024-05-30 15:51:51|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:51:51|   DEBUG|testAction.py[:57]|sniper
2024-05-30 15:51:51|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:51:51|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:51:51|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:51:51|   DEBUG|testAction.py[:57]|sniper
2024-05-30 15:51:51|   DEBUG|testAction.py[:58]|111111
2024-05-30 15:51:51|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:51:51|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2024-05-30 15:51:51|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2024-05-30 15:51:51|   DEBUG|testAction.py[:57]|apple
2024-05-30 15:51:51|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:51:51|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:51:51|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:51:51|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:51:51|   DEBUG|testAction.py[:57]|aaaa
2024-05-30 15:51:51|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:51:51|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:51:51|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:51:51|   DEBUG|testAction.py[:57]|bbbb
2024-05-30 15:51:51|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:51:51|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:51:51|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:51:51|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:51:51|   DEBUG|testAction.py[:57]|cccc
2024-05-30 15:51:51|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:51:51|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:51:52|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:51:52|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:51:52|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:51:52|   DEBUG|testAction.py[:57]|dddd
2024-05-30 15:51:52|   DEBUG|testAction.py[:58]|123456
2024-05-30 15:51:52|    INFO|testAction.py[:78]|response json: {'code': 0}
2024-05-30 15:51:52|    INFO|testAction.py[:105]|载入主页面...
2024-05-30 15:51:52|   ERROR|testAction.py[:148]|日期不在允许范围内
Traceback (most recent call last):
  File "D:\pyCharm\pycharm\testProject\testProject\testAction.py", line 131, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2024-05-30 15:51:52|   DEBUG|testAction.py[:57]|eeee
2024-05-30 15:51:52|   DEBUG|testAction.py[:58]|123456
